version: '3.8'

services:
  frontend-user:
    build:
      context: ./frontend-user
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: unless-stopped
    container_name: ecommerce-h5
